const routeCache=new Map();
window.findImageRoute=function(img,start,exits,hazards){
  const hazardKey=hazards.map(h=>`${h.item[0]}:${h.scale}`).join('|'),cacheKey=`${img.currentSrc}|${start.join(',')}|${hazardKey}`;
  if(routeCache.has(cacheKey))return routeCache.get(cacheKey);
  const N=100,canvas=document.createElement('canvas');canvas.width=N;canvas.height=N;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,N,N);const pixels=ctx.getImageData(0,0,N,N).data,key=(x,y)=>x+','+y,cell=p=>[Math.round(p[0]/100*(N-1)),Math.round(p[1]/100*(N-1))];
  const wall=(x,y)=>{if(x<0||y<0||x>=N||y>=N)return true;const i=(y*N+x)*4,r=pixels[i],g=pixels[i+1],b=pixels[i+2];if(r<100&&g<100&&b<100)return true;const px=x/(N-1)*100,py=y/(N-1)*100;return hazards.some(h=>Math.hypot(px-h.item[2],py-h.item[3])<h.scale*5.4+4)};
  const nearest=p=>{const c=cell(p);if(!wall(...c))return c;for(let radius=1;radius<12;radius++)for(let y=-radius;y<=radius;y++)for(let x=-radius;x<=radius;x++){if(Math.abs(x)!==radius&&Math.abs(y)!==radius)continue;const q=[c[0]+x,c[1]+y];if(!wall(...q))return q}return c};
  const source=nearest(start),goals=new Map();exits.forEach(exit=>goals.set(key(...nearest([exit[1],exit[2]])),exit));const queue=[source],came=new Map(),seen=new Set([key(...source)]);let found=null;
  for(let head=0;head<queue.length&&!found;head++){const current=queue[head],currentKey=key(...current);if(goals.has(currentKey)){found={cell:current,exit:goals.get(currentKey)};break}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const next=[current[0]+dx,current[1]+dy],nextKey=key(...next);if(seen.has(nextKey)||wall(...next))continue;seen.add(nextKey);came.set(nextKey,currentKey);queue.push(next)}}
  if(!found){routeCache.set(cacheKey,null);return null}const path=[];let point=found.cell;while(point){path.push([point[0]/(N-1)*100,point[1]/(N-1)*100]);const previous=came.get(key(...point));point=previous?previous.split(',').map(Number):null}path.reverse();const simplified=path.filter((p,i,a)=>i===0||i===a.length-1||!((a[i-1][0]===p[0]&&p[0]===a[i+1][0])||(a[i-1][1]===p[1]&&p[1]===a[i+1][1])));simplified.unshift(start);simplified.push([found.exit[1],found.exit[2]]);const result={exit:found.exit,path:simplified};routeCache.set(cacheKey,result);return result;
};
